### ISSUE TITLE
Does creation of Lucene Docuement adds actual image to docuement

### ISSUE THREAD

**Issue by jforjava1981** [dermotte/LIRE#28]
Does following call store actual image in lucene document. I guess not. I saw the source however just want to confirm.

globalDocumentBuilder.createDocument(img, imageFilePath);

Thanks,
Shailesh

**Comment by dermotte** [comment]
Dear Shailesh,

This is something that should not be handled as a issue. Please consult the documentation on issues in Github here: https://help.github.com/articles/about-issues/

I'd say: post it to the mailing list. 

regards,
  Mathias
