### ISSUE TITLE
missing method

### ISSUE THREAD

**Issue by vishalezen** [dermotte/LIRE#29]
Hi,
I am using the Lire for SIFT extraction and to construct BagofVisual Words.
But in DocumentBuilderFactory the following methods are not present which are used in indexing.java getEdgeHistogramBuilder();
getJCDDocumentBuilder();
getColorLayoutBuilder();

Any suggestions would be of great help...
Thanks.

**Comment by dermotte** [comment]
Hi!

These functions are there for historical reasons from a time when LIRE only supported global features. With the 1.0 release candidate the processing chain involves different steps. I suggest checking https://github.com/dermotte/LIRE/blob/master/src/main/docs/developer-docs/docs/createindex.md for how to extract local features. It can now be easily done with ParallelIndexer.

**Comment by vishalezen** [comment]
Thanks for the information :)
