### ISSUE TITLE
online demo link is not accessible

### ISSUE THREAD

**Issue by Artgit** [dermotte/LIRE#32]
I'm looking for CBIR engine something like LIRE. Right now I'd like to see the Online Demo application but unfortunately demo link is not accessible http://demo-itec.uni-klu.ac.at/liredemo/ 

Where I can see the actual demo ?

**Comment by dermotte** [comment]
Please use the mailing list for questions. This is the issue tracker dealing with things like "LIRE crashes when open file XY", not a help forum.
