### ISSUE TITLE
Change lucene core version in pom.xml

### ISSUE THREAD

**Issue by rsisto** [dermotte/LIRE#37]
The actual version should be 6.2.0 (it's pointing to 5.2.1)

**Comment by dermotte** [comment]
Hi! Absolutely, however, I've never used Maven, so all things related to Maven are contributed. I'd gladly accept a pull request.

cheers, 
Mathias

**Comment by rsisto** [comment]
Great!
I'm on it :)

Cheers!

--
*Ing. Rafael Sisto*
Ingeniero en Computación
[image: View Rafael Sisto's profile on LinkedIn]
<http://uy.linkedin.com/in/rafaelsisto>

**Comment by rsisto** [comment]
Mathias,

I also want to tell you that we're evaluating the tool to integrate it to a
project.
In case we move forward, I'd love to migrate everything you have to maven
or maybe work on some TODOs, what do you think?

Cheers!

--
*Ing. Rafael Sisto*
Ingeniero en Computación
[image: View Rafael Sisto's profile on LinkedIn]
<http://uy.linkedin.com/in/rafaelsisto>

**Comment by dermotte** [comment]
Hi! I think that's a great idea. I pondered with the idea of moving to gradle but I never really found the time to get knee deep into gradle ... I'm still onto ant. However, afaik gradle goes very well with maven and if the gradle move happens, it's much less work when maven is up and running. All other additions are most welcome. I can offer to test new features and help out on the inner workings of things in LIRE.

**Comment by rsisto** [comment]
Hi Mathias, how are you?

I wrote a private email to mathias at juggle dot at. Is that correct?

Can you please confirm you received it? I'd like to get in touch with you.

Thanks,

--
*Ing. Rafael Sisto*
Ingeniero en Computación
[image: View Rafael Sisto's profile on LinkedIn]
<http://uy.linkedin.com/in/rafaelsisto>

**Comment by dermotte** [comment]
Please don't use the issue tracker for non-issues 🤔
