### ISSUE TITLE
FileNotFound exception

### ISSUE THREAD

**Issue by HelloPig** [dermotte/LIRE#42]
I've created the index using the SurfExtractor like this
`ParallelIndexer indexer = new ParallelIndexer(6, args2[0], args2[1]);
indexer.addExtractor(SurfExtractor.class);
indexer.run();`
and then I create a searcher
`ImageSearcher searcher = new GenericFastImageSearcher(30, SurfExtractor.class, new BOVW(), 128, "E:\\workspace\\LireSimple\\codebooks");`
and it run out an error
`java.io.FileNotFoundException: E:\workspace\LireSimple\codebooks\null`
seems that the **SurfExtractor** haven't overwrite the method **getFieldName**

is there an example to do an search using SURF in LIRE?

**Comment by dermotte** [comment]
Hi HelloPig!

Please note that this is the issue tracker and not the development mailing list, which actually handles things like this. 

best,
Mathias
