### ISSUE TITLE
Question regarding Image Search

### ISSUE THREAD

**Issue by theTIOM** [dermotte/LIRE#43]
Hi, I am a Ph.D. student at Purdue University and have a question regarding image searching. 
I am using your sample application code "Searcher.java," and applied PHOG descriptor.
Test results are below.

1221.0: 	C:\Set\1\K-021.jpg
1278.0: 	C:\Set\1\K-016.jpg
1495.0: 	C:\Set\1\K-013.jpg
1528.0: 	C:\Set\1\K-002.jpg
1584.0: 	C:\Set\1\K-003.jpg
1636.0: 	C:\Set\1\K-001.jpg
1636.0: 	C:\Set\1\K-017.jpg
1680.0: 	C:\Set\1\K-018.jpg
1712.0: 	C:\Set\1\K-014.jpg
1725.0: 	C:\Set\1\K-019.jpg
1732.0: 	C:\Set\1\K-008.jpg
1736.0: 	C:\Set\1\K-015.jpg
1743.0: 	C:\Set\1\K-007.jpg
1769.0: 	C:\Set\1\K-005.jpg
1771.0: 	C:\Set\1\K-020.jpg
1807.0: 	C:\Set\1\K-004.jpg
1853.0: 	C:\Set\1\K-010.jpg
1859.0: 	C:\Set\1\K-011.jpg
1861.0: 	C:\Set\1\K-012.jpg
1907.0: 	C:\Set\1\K-009.jpg
2220.0: 	C:\Set\1\K-006.jpg

My question is the meaning of these score numbers.
I realized that score is zero when target image and index image are same.
Actually, I would like to present this score 1.0 (Max) to 0 (min).
For this, what should I do? What parts do I have to see and revise?

**Comment by dermotte** [comment]
Hi!

Please use the mailing list for questions like these. This is not an "issue" but a developer question. 

However, while I'm writing there's the answer too. You can find the distance function generating these distance values in the feature implementations. In this specific case its

https://github.com/dermotte/LIRE/blob/master/src/main/java/net/semanticmetadata/lire/imageanalysis/features/global/PHOG.java#L378

calling MetricUtils.L1(...) 

cheers,
Mathias
