### ISSUE TITLE
Using openCV with LIRe,index file is too large, very slow, how to improve?

### ISSUE THREAD

**Issue by bukebuhao** [dermotte/LIRE#47]
Codebook set to 8,20w data, index file 800m,
Search for each picture about 3s

**Comment by dermotte** [comment]
Hi! This is not an issue with LIRE but a configuration and usage problem. Please do not use the issue tracker for configuration and usage questions. We have the mailing list lire-dev for that https://groups.google.com/forum/#!forum/lire-dev 

happy easter,
Mathias
