### ISSUE TITLE
The POM for net.semanticmetadata:lire:jar:0.9.4-fg-SNAPSHOT is missing, no dependency information available

### ISSUE THREAD

**Issue by Divyam53** [dermotte/LIRE#52]
The POM for net.semanticmetadata:lire:jar:0.9.4-fg-SNAPSHOT is missing, no dependency information available

**Comment by Divyam53** [comment]
I have added manually and the error has gone.

**Comment by dermotte** [comment]
There is no real Maven support in LIRE. As with the last large update Gradle is recommended.
