### ISSUE TITLE
About the docs

### ISSUE THREAD

**Issue by leafjungle** [dermotte/LIRE#53]
Is there any docs talks about the theory of LIRE? such as the Product Quantization,  clustering, inverted index, distance measure, etc? And how a new image is added into the index ?

**Comment by dermotte** [comment]
Please do not use the issue tracker for asking questions. Please also check the docs here: https://github.com/dermotte/LIRE/blob/master/src/main/docs/developer-docs/docs/index.md there is a section on this issue.
