### ISSUE TITLE
Improvement of sleep in loop

### ISSUE THREAD

**Issue by o0lwj0o** [dermotte/LIRE#66]
Hi, I found an interesting case in this project.
It has “Thread.sleep()” in a “while(true)” loop. I found some discussion in Stackoverflow and other website. It can be refactored by using a executor service.
https://ejrh.wordpress.com/2012/07/13/sleeping-in-loops-considered-harmful/
https://stackoverflow.com/questions/3535754/netbeans-java-new-hint-thread-sleep-called-in-loop
or
Maybe use CountDownLatch.await to automatically awake and shutdown.

Detailed websites and lines:

50 | https://github.com/dermotte/LIRE/blob/master/samples/liredemo/src/main/java/liredemo/flickr/FlickrDownloadThread.java

Best regards

**Comment by dermotte** [comment]
Hi!

Thanks for pointing that out! Like so many other classes this is just a quick and dirty approach to get photos from Flickr, and I'm not sure that the new owner of Flickr still supports the API :-) I'll definitely keep it in mind for the next time!

cheers,
Mathias
